### ISSUE TITLE
AttributeError: module 'cv2.cv2' has no attribute 'TrackerKCF_create'

### ISSUE THREAD

**Issue by HangJie720** [opencv/opencv#15723]

**Comment by HangJie720** [comment]
tracker = cv2.Tracker_create(tracker_type),this api not found, that's why?

**Comment by berak** [comment]
>my opencv-python version is 3.4.5.20
opencv-contrib-python version is also 3.4.5.20.

if you use pip, please ONLY install opencv-contrib-python , not both.

**Comment by HangJie720** [comment]
> I have pip uninstall opencv-python, only the opencv-contrib-python, why still have not 'Tracker_create' interface. My device is MacOS 10.13.5.
> >> import cv2 >> cv2.Tracker_create()
> Traceback (most recent call last): File "<stdin>", line 1, in <module> AttributeError: module 'cv2.cv2' has no attribute 'Tracker_create'
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "berak"<notifications@github.com>; 发送时间: 2019年10月17日(星期四) 下午4:24 收件人: "opencv/opencv"<opencv@noreply.github.com>; 抄送: "JackHay"<1339327861@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [opencv/opencv] AttributeError: module 'cv2.cv2' has no attribute'TrackerKCF_create' (#15723) my opencv-python version is 3.4.5.20 opencv-contrib-python version is also 3.4.5.20. if you use pip, please ONLY install opencv-contrib-python , not both. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you very much, problem have been solved.

**Comment by gopalkalpande** [comment]
I'm using opencv 4.1.1 and encountered the same error... if anyone knows please help.

**Comment by gopalkalpande** [comment]
pip3 install opencv-contrib-python


This solved the error for me.

**Comment by BitbeyHub** [comment]
> > my opencv-python version is 3.4.5.20
> > opencv-contrib-python version is also 3.4.5.20.
> 
> if you use pip, please ONLY install opencv-contrib-python , not both.

You are really awesome dude!

**Comment by luys8611** [comment]
Hello. I'm using Ubuntu 18.04 and opencv-contrib-python==3.4.5.20
I'm having above issue still now.
```
cv2.Tracker_create()
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
AttributeError: module 'cv2.cv2' has no attribute 'Tracker_create'
```

How can I solve this?
Please help me.

**Comment by kamalojasv181** [comment]
Hi, I need to import cv2 as well in a project and if i uninstall opencv-python, I can no longer import cv2. Keeping both opencv-python and opencv-contrib-python still shows the same error

versions 
opencv-python-4.2.0.34
opencv-contrib-python 1.18.1

**Comment by Alien-X717** [comment]
> Hi, I need to import cv2 as well in a project and if i uninstall opencv-python, I can no longer import cv2. Keeping both opencv-python and opencv-contrib-python still shows the same error
> 
> versions
> opencv-python-4.2.0.34
> opencv-contrib-python 1.18.1

uninstall both ("opencv-python" and "opencv-contrib-python" ) and then install "opencv-contrib-python"

**Comment by VoNhatVinh** [comment]
I uninstall opencv-contrib-python==3.4.14.51 and reinstall it. Works for me!

**Comment by AliKJaber** [comment]
First, pip uninstall opencv-contrib-python, and then, pip install opencv-contrib-python. Its work fine for me and solved all related Tracker issues.

**Comment by Saugatkafley** [comment]
Uninstalling the both opencv-python and opencv-contrib-python ==4.5.5.62  and re-installing only the contrib didn't solved the issue ..

**Comment by Saugatkafley** [comment]
I just downgraded to opencv-contrib-python ==4.4.0.46 and it resolved it.

**Comment by SIDDHARTH-S-001** [comment]
uninstall opencv-python
uninstall opencv-contrib-python
then do 
pip3 install opencv-contrib-python
this worked for me

**Comment by Surajj4837-th** [comment]
> I just downgraded to opencv-contrib-python ==4.4.0.46 and it resolved it.

This worked for me.

**Comment by luoxue-star** [comment]
> 首先，pip 卸载 opencv-contrib-python，然后，pip 安装 opencv-contrib-python。它对我来说工作正常，并解决了所有相关的 Tracker 问题。

Yes,it also helps me.Thank you.

**Comment by ilkin94** [comment]
Delete opencv-python and opencv-contrib. Then install opencv-contrib. This worked for me.

**Comment by Curious-Utkarsh** [comment]
> > Hi, I need to import cv2 as well in a project and if i uninstall opencv-python, I can no longer import cv2. Keeping both opencv-python and opencv-contrib-python still shows the same error
> > versions
> > opencv-python-4.2.0.34
> > opencv-contrib-python 1.18.1
> 
> uninstall both ("opencv-python" and "opencv-contrib-python" ) and then install "opencv-contrib-python"

**Comment by Curious-Utkarsh** [comment]
Delete opencv-python and opencv-contrib. Then install opencv-contrib. 

tracker = cv2.legacy_TrackerMOSSE.create()

this worked for me.

**Comment by ssukgodblyat** [comment]
> pip3 install opencv-contrib-python
> 
> This solved the error for me.

which version of opencv-contrib did you install?
i'm using opencv 4.1.1 and i have same problem.
