### ISSUE TITLE
EXR read/write not supporting alpha channel

### ISSUE THREAD

**Issue by MrMabulous** [opencv/opencv#16115]
Looks like grfmt_exr has no support for alpha channel currently. Is there a good reason this has been omitted from the implementation?

**Comment by YgabrielsY** [comment]
Currently, I also have to rely on using the OpenEXR library directly because of missing alpha channel support in opencv. I think it would be very helpful to have, especially since the OpenEXR library seems to support an alpha channel similar/equally to any other color channel

**Comment by asmorkalov** [comment]
OpenCV is comunity driven project. Feel free to propose PR with alpha channel support for EXR to OpenCV code base.

**Comment by asmorkalov** [comment]
@vpisarev @alalek I need your advice for the task. Current reader for OpenEXR ignores alpha channel and returns `cv::Mat` with type `32FC3` with flag `IMREAD_UNCHANGED`. It happens, even alpha channel is present in input file. I can introduce logic to check alpha channel and return `32FC4` for this case, but it breaks compatibility. What do you think about it?

**Comment by alalek** [comment]
Do you have sample image?

> IMREAD_UNCHANGED
> ignores alpha channel
> 32FC3

I believe it is a bug, so it should be fixed.

**Comment by raaldrid** [comment]
Hi, @MrMabulous, @YgabrielsY, I'm looking into adding alpha support to the OpenEXR reader.  Can you please provide sample OpenEXR images with RGBA channels which appear visually different with/without the alpha channel.  Thank you!

**Comment by sbmdv** [comment]
Hello @raaldrid, thank you for looking at this issue! Here are some images with and without alpha channels, hope it helps: [EXR_samples.zip](https://github.com/opencv/opencv/files/5988047/EXR_samples.zip)

**Comment by raaldrid** [comment]
@sbmdv Thank you!  Those are great.  The second image is particularly good because I can confirm the visual difference when alpha is missing.  

Are you seeking support for RGBA files only, or alpha channel support for Y and Y RY BY (Luminance Chroma) files also?  From what I have read it looks like that combination is possible: Y RY BY with A or Y with A.  Are you able to provide test images for Y RY BY w/ & w/o A, and Y w/ & w/o A?

Thanks very much!

**Comment by sbmdv** [comment]
I'm glad the samples have been of some use. 
While I've only ever used RGBA files myself (and therefore only need support for those), I have converted the second image to the channel formats you asked for: [EXR_samples2.zip](https://github.com/opencv/opencv/files/6002101/EXR_samples2.zip)

Let me know if you need any more samples.

**Comment by raaldrid** [comment]
Beautiful!  Thank you kindly.

**Comment by raaldrid** [comment]
Hi @sbmdv, I need your input please!  I have implemented supporting the alpha channel.  Interestingly when I read an exr image with alpha and then write the image back out stripping the alpha channel (testing different flag support), the image looks the same as the original input.  Is that what you would expect?  I'm not an expert with image creation/viewing softwares (Adobe, etc).  
Attached are a few of the test images you provided read in and written out by the modified OpenCV code, some preserving alpha and others removing it:  

[EXR Testing Ouput.zip](https://github.com/opencv/opencv/files/6024376/EXR.Testing.Ouput.zip)

Thank you.

**Comment by sbmdv** [comment]
Yes, this result is expected as the "2_alpha" image actually does not have the same RGB information as the "2_no_alpha" image. One has a black background and the other has a bluish one. So without the alpha channel that background will still appear black. Oops, my bad. Here is a better RGBA test image which should look different after stripping the alpha channel: [2_added_alpha.zip](https://github.com/opencv/opencv/files/6025654/2_added_alpha.zip)

Anyways it seems like your implementation works, as the images you uploaded look perfectly fine! Thank you very much!

**Comment by raaldrid** [comment]
Thank you @sbmdv.  I ran your latest 2_added_alpha test file through (which looks visually identical to 2_no_alpha in my EXR viewer) and removed the alpha channel and it looks visully the same as the original 2_added_alpha:   
[2_added_alpha.written.removedalpha.zip](https://github.com/opencv/opencv/files/6038129/2_added_alpha.written.removedalpha.zip)

For my information: Is your image editor is writing the files with premultiplied alpha?  That might explain why they look the same.

**Comment by sbmdv** [comment]
Yes, apparently the Photoshop plug-in I used (ProEXR) writes EXR files with premultiplied alpha.

Regarding the two images being visually identical: Can you confirm that your EXR viewer doesn't ignore the alpha channel? I've used exrdisplay in the past for testing purposes and it seems like it completely disregards the alpha from the EXR files I feed it.

**Comment by raaldrid** [comment]
@sbmdv Thank you for offering that my EXR viewer might be ignorning the alpha channel.  I could not find that information on my viewer (OpenHDR).  I was able to download a better viewer (Tacent View) and now I can see the alpha.  Yay :)  

I'll polish the unit test code for this change and make a pull request soon.  Thank you very much for your help!

**Comment by sbmdv** [comment]
@raaldrid No worries, and thank _you_ for doing the hard work!

**Comment by raaldrid** [comment]
@alalek Code review on this PR please?  It appears to be passing all required builds (non Jenkins).  PR https://github.com/opencv/opencv/pull/19655

**Comment by JohnG0024** [comment]
> Currently, I also have to rely on using the OpenEXR library directly because of missing alpha channel support in opencv. I think it would be very helpful to have, especially since the OpenEXR library seems to support an alpha channel similar/equally to any other color channel
@YgabrielsY Hi, do you happen to know how to add an alpha channel and write to .exr using OpenEXR python library?
