### ISSUE TITLE
opencv 4.1.2 java Mac OpenCV: not authorized to capture video (status 0), requesting...

### ISSUE THREAD

**Issue by lvxingtu** [opencv/opencv#16255]
OpenCV: not authorized to capture video (status 0), requesting...
I follow tutorial https://opencv-java-tutorials.readthedocs.io/en/latest/index.html and run the demo from https://github.com/opencv-java/getting-started FXHelloCV.
```key code
private VideoCapture capture = new VideoCapture();
...
capture.open(cameraId); 
```

when run to capture.open(cameraId); 
the application crash and print error
```
 OpenCV: not authorized to capture video (status 0), requesting...
```

It seems Mac authorized problem and I speed a lot of time but can't solve it.

I also try python from terminal
```python
import cv2
 
cap = cv2.VideoCapture(0)
i = 0
while (1):
    ret, frame = cap.read()
    k = cv2.waitKey(1)
    if k == 27:
        break
    elif k == ord('s'):
        cv2.imwrite('/Users/step/Desktop' + str(i) + '.jpg', frame)
        i += 1
    cv2.imshow("capture", frame)
cap.release()
cv2.destroyAllWindows()
```
it also have same problem but it will pop up a system window show allow camera access from terminal, I choose allow and it can run without problem.
```
OpenCV: not authorized to capture video (status 0), requesting...
OpenCV: camera failed to properly initialize!
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    cv2.imshow("capture", frame)
cv2.error: OpenCV(4.1.2) /tmp/opencv-20191229-21806-57s1wf/opencv-4.1.2/modules/highgui/src/window.cpp:376: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'
```
I also try run jar from terminal
but with java , the problem still exist, and no pop up window I can choose.

different error behavior, java application exit when the error happen, but python seems still running when happen.
java-version: openjdk version "13.0.1-BellSoft" 2019-10-15
mac-version: macOS Catalina 10.15.2

**Comment by balachandarsv** [comment]
I guess, this isn't a OpenCV issue.

I too had faced this. This is what I did. 

`VideoCapture capture = new VideoCapture();
while(true){
capture.open();
}`

Run this code once separately, and you would be prompted with the mac authorization. 

This is not a solution, but i solved it this way.

**Comment by lvxingtu** [comment]
Unfortunately this does not work for me.

**Comment by alalek** [comment]
You need to authorize your application (perhaps whole "java") to access cameras.
Refer to macOS documentation about privacy configuration.

This can't be fixed in OpenCV. Closing.

**Comment by YasPHP** [comment]
**Had same issue and found that meeting all these steps made it work on mac:**
- make sure it's `cap = cv2.VideoCapture(0)` if using default mac camera and if using more external `x` cameras, scale and include VideoCapture(1), 2, 3, etc.
- don't forget to release the video source at the proper time by calling the `release()` method or else it will leave your camera unusable and you'll have to either restart your mac or reset the system entirely to recover the camera with `sudo killall VDCAssistant`
- running main program directly on terminal vs pycharm run worked
- make sure to close webcam window at end with 
` cv2.destroyAllWindows()
  cap.release()
  break`
- have opencv-contrib-python properly installed via your requirements.txt

These are just the basics you could be missing and leading it to error _or_ it could be something else but this is a good checklist for a first step. Good luck!

**Comment by bilalkhann16** [comment]
If you're using Anaconda, you need to give the complete path.
Try: `/Users/user_name/anaconda3/envs/env_name/bin/pip install opencv-contrib-python`

**Comment by iMuhammadwaseem** [comment]
> **Had same issue and found that meeting all these steps made it work on mac:**
> 
> * make sure it's `cap = cv2.VideoCapture(0)` if using default mac camera and if using more external `x` cameras, scale and include VideoCapture(1), 2, 3, etc.

 **(I TRIED BUT STILL THE PROBLEM PERSIST)**

> * don't forget to release the video source at the proper time by calling the `release()` method or else it will leave your camera unusable and you'll have to either restart your mac or reset the system entirely to recover the camera with `sudo killall VDCAssistant`.  

**(CAN YOU PLEASE EXPLAIN ME HOW TO ACHIEVE THIS, COZ I AM NEW TO MAC ENVIRONMENT? THOUGH I AM NOT SURE WHETHER THIS IS THE PROBLEM IN MY MAC I JUST WANT TO TRY IT)**

> * running main program directly on terminal vs pycharm run worked. 

**(YES MY CODE  IS WORKING IN TERMINAL, BUT I NEED IT TO WORK IN SPYDER FOR EASY ACCESSIBILITY)**

> * make sure to close webcam window at end with
>   ` cv2.destroyAllWindows() cap.release() break`

> * have opencv-contrib-python properly installed via your requirements.txt  

**(I INSTALLED THIS DIRECTLY BY GIVING THE FULL PATH OF ENVIRONMENT AND PIP COMMAND, I DIDNT  USE REQ FILE, IT IS NOT A PROBLEM RIGHT?)**
> 
> These are just the basics you could be missing and leading it to error _or_ it could be something else but this is a good checklist for a first step. Good luck!


**THIS IS WHAT MY TERMINAL SHOWS**

<img width="713" alt="Screenshot 2022-04-24 at 9 42 40 AM" src="https://user-images.githubusercontent.com/85298297/164956286-729a52a8-910a-4497-89df-92ce4ddbcc7b.png">

**Comment by ilknurakcay** [comment]
Did you solved this problem?

**Comment by youngsiiimba** [comment]
Run your code using the default "Terminal", then you'll be prompted with Mac authorization. I keep getting that error when trying to run my code using "iTerm2/OhMyZsh" which is a custom terminal.

**Comment by hrana123** [comment]
How to acccess webcam in netbeans using jdk 8 ?

**Comment by hrana123** [comment]
OpenCV: not authorized to capture video (status 0), requesting...
OpenCV: can not spin main run loop from other thread, set OPENCV_AVFOUNDATION_SKIP_AUTH=1 to disable authorization request and perform it in your application.
OpenCV: camera failed to properly initialize!



how to solve this error.
i used jdk 11 and jdk 8 but not work.
