### ISSUE TITLE
YoloV7 not working using OpenCV 4.5.5 and Inference Engine as preferable backend

### ISSUE THREAD

**Issue by cesarpgouveia** [opencv/opencv#22990]
### System Information

OpenCV version: 4.5.5
Operating System / Platform: Windows 10
CUDA version: 11.2
CuDNN version: 8.1.0
Inference Engine version (OpenVINO): 2021.4.689

### Detailed description

Hey, 

I built OpenCV 4.5.5 with support for CUDA 11.2 and OpenVINO 2021.4.689. After that, I made a quick demo code to test the new YoloV7 model. Basically my goal is to run YoloV7 using both OPENCV, INFERENCE_ENGINE and CUDA backends. The code crashes with the following exception when **INFERENCE_ENGINE** is used:

Unhandled exception at 0x00007FFEFB78CD29 in YoloTest2.exe: Microsoft C++ exception: ngraph::NodeValidationFailure at memory location 0x00000019903FB6A8.

while passing through this piece of code (**scale_layer.cpp**):

```
#if INF_ENGINE_VER_MAJOR_GT(INF_ENGINE_RELEASE_2021_2)
            node = std::make_shared<ngraph::op::v1::Multiply>(node, weight, ngraph::op::AutoBroadcastType::NUMPY);
#else
```

Any other information that you need feel free to ask and thank you so much for any help you can provide.

### Steps to reproduce

Code sample can be found here: 
[YoloTest2.zip](https://github.com/opencv/opencv/files/10263545/YoloTest2.zip)

Yolo v7 models can be found here:
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/307_YOLOv7

I used the single batch version 256x320 input size (full, not tiny): **yolov7_256x320.onnx**

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by fengyuentau** [comment]
You could have a try with OpenCV 4.6.0. I can confirm that I can load and infer the model with the OPENCV backend.

**Comment by cesarpgouveia** [comment]
Hey @fengyuentau, thanks for the help, I already tried with OpenCV 4.6.0 and the same issue happens. Yes, I have no problem running the model with both OpenCV and CUDA backends, however, INFERENCE_ENGINE seems to be the issue here.

**Comment by fengyuentau** [comment]
@alalek Could you take a look at this issue about Inference Engine if you are available?

**Comment by fengyuentau** [comment]
@alalek Could you take a look at this issue about Inference Engine if you are available?

**Comment by cesarpgouveia** [comment]
Hey @fengyuentau, today I tried to build OpenCV 4.7.0 with the new OpenVINO version (2022.3) and YoloV7 is working with the INFERENCE_ENGINE backend. Not sure if what did the trick was updating OpenVINO from 2021 to 2022 or OpenCV from 4.6.0 to 4.7.0, either way, my issue is solved. Anyway thanks for the help!

**Comment by qlong1505** [comment]
> 

@cesarpgouveia  I tried you example code with OpenCV 4.7.0 build with openvino (2022.3) but it still crashes with INFERENCE_ENGINE backend. Have you modified any part in your code sample to get it worked. Tks.

**Comment by cesarpgouveia** [comment]
Hey @qlong1505, could you please let me know which flags you used to compile your OpenCV 4.7.0?
