### ISSUE TITLE
`cv2.VideoCapture` does not raise exception immediately after an error occurs

### ISSUE THREAD

**Issue by ShyAssassin** [opencv/opencv#23207]
### System Information

OpenCV python version: 4.6.0.66
Operating System: Windows 11
Python version: 3.11

### Detailed description

If a camera stream is not found or a camera is offline (unreachable IP address) opencv will throw an connection error connection of `-138` and softlock the main thread for around 30 seconds until an exception is thrown. 
For some reason after the error is encountered it takes opencv a very long time before realizing this and actually throwing an exception. 
At times no exception is even thrown even with `cv2.VideoCapture.setExceptionMode(True)` set
![image](https://user-images.githubusercontent.com/49711232/215896217-ae11b028-faac-4350-b7b7-63f7de8b0645.png)

### Steps to reproduce

```python
import cv2
from datetime import datetime
while True:
    try:
        print(f"{datetime.now().strftime('%H:%M:%S')} || Trying to connect to camera")
        camera = cv2.VideoCapture("http://10.0.0.114")
        camera.setExceptionMode(True)
        if camera.isOpened():
            print("Camera connected!")
            break
        print(f"{datetime.now().strftime('%H:%M:%S')} || Failed to connect to camera, no exception was thrown")
    except:
        print(f"{datetime.now().strftime('%H:%M:%S')} || Failed to connect to camera, exception was thrown")  # wont run
```

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by dkurt** [comment]
what about `camera.set(cv.CAP_PROP_OPEN_TIMEOUT_MSEC, N)`?

**Comment by ShyAssassin** [comment]
When trying to use `camera.set(cv.CAP_PROP_OPEN_TIMEOUT_MSEC, 1000)` an error of `cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap.cpp:425: error: (-2:Unspecified error) could not set prop 53 = 1000.000000 in function 'cv::VideoCapture::set` is thrown

Here is the output of `cv2.getBuildInformation`
```
General configuration for OpenCV 4.7.0 =====================================
  Version control:               4.7.0

  Platform:
    Timestamp:                   2022-12-29T19:12:01Z
    Host:                        Windows 10.0.17763 AMD64
    CMake:                       3.24.2
    CMake generator:             Visual Studio 14 2015
    CMake build tool:            MSBuild.exe
    MSVC:                        1900
    Configuration:               Debug Release

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (16 files):         + SSSE3 SSE4_1
      SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (0 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (4 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (32 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2

  C/C++:
    Built as dynamic libs?:      NO
    C++ standard:                11
    C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe  (ver 19.0.24245.0)
    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /wd4819 /MP  /MT /O2 /Ob2 /DNDEBUG
    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /wd4819 /MP  /MTd /Zi /Ob0 /Od /RTC1
    C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
    C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /MP   /MT /O2 /Ob2 /DNDEBUG
    C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /MP /MTd /Zi /Ob0 /Od /RTC1
    Linker flags (Release):      /machine:x64  /NODEFAULTLIB:atlthunk.lib /INCREMENTAL:NO  /NODEFAULTLIB:libcmtd.lib /NODEFAULTLIB:libcpmtd.lib /NODEFAULTLIB:msvcrtd.lib
    Linker flags (Debug):        /machine:x64  /NODEFAULTLIB:atlthunk.lib /debug /INCREMENTAL  /NODEFAULTLIB:libcmt.lib /NODEFAULTLIB:libcpmt.lib /NODEFAULTLIB:msvcrt.lib
    ccache:                      NO
    Precompiled headers:         YES
    Extra dependencies:          wsock32 comctl32 gdi32 ole32 setupapi ws2_32
    3rdparty dependencies:       libprotobuf ade ittnotify libjpeg-turbo libwebp libpng libtiff libopenjp2 IlmImf zlib quirc ippiw ippicv

  OpenCV modules:
    To be built:                 calib3d core dnn features2d flann gapi highgui imgcodecs imgproc ml objdetect photo python3 stitching video videoio
    Disabled:                    world
    Disabled by dependency:      -
    Unavailable:                 java python2 ts
    Applications:                -
    Documentation:               NO
    Non-free algorithms:         NO

  Windows RT support:            NO

  GUI:                           WIN32UI
    Win32 UI:                    YES
    VTK support:                 NO

  Media I/O:
    ZLib:                        build (ver 1.2.13)
    JPEG:                        build-libjpeg-turbo (ver 2.1.3-62)
      SIMD Support Request:      YES
      SIMD Support:              NO
    WEBP:                        build (ver encoder: 0x020f)
    PNG:                         build (ver 1.6.37)
    TIFF:                        build (ver 42 - 4.2.0)
    JPEG 2000:                   build (ver 2.4.0)
    OpenEXR:                     build (ver 2.3.0)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    DC1394:                      NO
    FFMPEG:                      YES (prebuilt binaries)
      avcodec:                   YES (58.134.100)
      avformat:                  YES (58.76.100)
      avutil:                    YES (56.70.100)
      swscale:                   YES (5.9.100)
      avresample:                YES (4.0.0)
    GStreamer:                   NO
    DirectShow:                  YES
    Media Foundation:            YES
      DXVA:                      YES

  Parallel framework:            Concurrency

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2020.0.0 Gold [2020.0.0]
           at:                   D:/a/opencv-python/opencv-python/_skbuild/win-amd64-3.7/cmake-build/3rdparty/ippicv/ippicv_win/icv
    Intel IPP IW:                sources (2020.0.0)
              at:                D:/a/opencv-python/opencv-python/_skbuild/win-amd64-3.7/cmake-build/3rdparty/ippicv/ippicv_win/iw
    Lapack:                      NO
    Eigen:                       NO
    Custom HAL:                  NO
    Protobuf:                    build (3.19.1)

  OpenCL:                        YES (NVD3D11)
    Include path:                D:/a/opencv-python/opencv-python/opencv/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python 3:
    Interpreter:                 C:/hostedtoolcache/windows/Python/3.7.9/x64/python.exe (ver 3.7.9)
    Libraries:                   C:/hostedtoolcache/windows/Python/3.7.9/x64/libs/python37.lib (ver 3.7.9)
    numpy:                       C:/hostedtoolcache/windows/Python/3.7.9/x64/lib/site-packages/numpy/core/include (ver 1.17.0)
    install path:                python/cv2/python-3

  Python (for build):            C:/ProgramData/chocolatey/bin/python2.7.exe

  Java:
    ant:                         NO
    JNI:                         C:/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk/8.0.352-8/x64/include C:/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk/8.0.352-8/x64/include/win32 C:/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk/8.0.352-8/x64/include
    Java wrappers:               NO
    Java tests:                  NO

  Install to:                    D:/a/opencv-python/opencv-python/_skbuild/win-amd64-3.7/cmake-install
-----------------------------------------------------------------
```

**Comment by ribeirompl-soldersmith** [comment]
Related regarding the use of timeout https://github.com/opencv/opencv-python/issues/788

**Comment by asmorkalov** [comment]
Related issue in Python bindings has been fixed.

**Comment by asmorkalov** [comment]
OpenCV uses 3rd party libraries for video codecs, e.g FFmpeg. The warning you see is produced by it. VideoCapture/FFmpeg tries to reconnect to camera several times to handle connectivity issues. You can define timeouts as dkurt proposed to reduce connection time.

**Comment by ShyAssassin** [comment]
> e

Even after updating to the latest `opencv-python` package and making sure it is using opencv version `4.18` or above the same error complaining about not being able to set the timeout prop is still present, i am still not able to set `CAP_PROP_READ_TIMEOUT_MSEC` or `CAP_PROP_READ_TIMEOUT_MSEC `

**Comment by ShyAssassin** [comment]
> > OpenCV uses 3rd party libraries for video codecs, e.g FFmpeg. The warning you see is produced by it. VideoCapture/FFmpeg tries to reconnect to camera several times to handle connectivity issues. You can define timeouts as dkurt proposed to reduce connection time.
> 
> Even after updating to the latest `opencv-python` package and making sure it is using opencv version `4.18` or above the same error complaining about not being able to set the timeout prop is still present, i am still not able to set `CAP_PROP_READ_TIMEOUT_MSEC` or `CAP_PROP_READ_TIMEOUT_MSEC` (i have only tested on windows)

**Comment by ShyAssassin** [comment]
Setting environment variables did not seem to alter the output i got, running this script
```python
import os
os.environ["OPENCV_LOG_LEVEL"] = "DEBUG"
os.environ["OPENCV_VIDEOIO_DEBUG"] = "1"
import cv2

camera = cv2.VideoCapture()
print(f"OpenCV: {cv2.getVersionString()}")
camera.setExceptionMode(True)
camera.set(cv2.CAP_PROP_OPEN_TIMEOUT_MSEC, 5000)
camera.open("http://localhost:8080")
```
i get the following error
```
OpenCV: 4.8.0
Traceback (most recent call last):
  File "c:\Users\Assassin\Documents\GitHub\ETVR-Backend\test.py", line 9, in <module>
    camera.set(cv2.CAP_PROP_OPEN_TIMEOUT_MSEC, 5000)
cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap.cpp:473: error: (-2:Unspecified error) could not set prop 53 = 5000.000000 in function 'cv::VideoCapture::set' 
```

**Comment by asmorkalov** [comment]
Could you share full log? It contains information about VideoCapture back-end. `cv.getBuildInformation()` output is useful
 too.

**Comment by ShyAssassin** [comment]
> Could you share full log? It contains information about VideoCapture back-end.

What i posted previously was the full output.
![image](https://github.com/opencv/opencv/assets/49711232/1e2c7b0f-b816-4ad9-bc25-8c1d921750bd)

I have run the script again and printed `cv.getBuildInformation()`

<details>
<summary>Build Information</summary>

```
General configuration for OpenCV 4.8.0 =====================================
  Version control:               4.8.0

  Platform:
    Timestamp:                   2023-06-30T11:22:01Z
    Host:                        Windows 10.0.17763 AMD64
    CMake:                       3.24.2
    CMake generator:             Visual Studio 14 2015
    CMake build tool:            MSBuild.exe
    MSVC:                        1900
    Configuration:               Debug Release

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (16 files):         + SSSE3 SSE4_1
      SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (0 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (7 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (35 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2

  C/C++:
    Built as dynamic libs?:      NO
    C++ standard:                11
    C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe  (ver 19.0.24247.2)
    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /wd4819 /MP  /MT /O2 /Ob2 /DNDEBUG
    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /wd4819 /MP  /MTd /Zi /Ob0 /Od /RTC1
    C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
    C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /MP   /MT /O2 /Ob2 /DNDEBUG 

    C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /MP /MTd /Zi /Ob0 /Od /RTC1 

    Linker flags (Release):      /machine:x64  /NODEFAULTLIB:atlthunk.lib /INCREMENTAL:NO  /NODEFAULTLIB:libcmtd.lib /NODEFAULTLIB:libcpmtd.lib /NODEFAULTLIB:msvcrtd.lib
    Linker flags (Debug):        /machine:x64  /NODEFAULTLIB:atlthunk.lib /debug /INCREMENTAL  /NODEFAULTLIB:libcmt.lib /NODEFAULTLIB:libcpmt.lib /NODEFAULTLIB:msvcrt.lib
    ccache:                      NO
    Precompiled headers:         YES
    Extra dependencies:          wsock32 comctl32 gdi32 ole32 setupapi ws2_32
    3rdparty dependencies:       libprotobuf ade ittnotify libjpeg-turbo libwebp libpng libtiff libopenjp2 IlmImf zlib quirc ippiw ippicv

  OpenCV modules:
    To be built:                 calib3d core dnn features2d flann gapi highgui imgcodecs imgproc ml objdetect photo python3 stitching video videoio
    Disabled:                    java world
    Disabled by dependency:      -
    Unavailable:                 python2 ts
    Applications:                -
    Documentation:               NO
    Non-free algorithms:         NO

  Windows RT support:            NO

  GUI:                           WIN32UI
    Win32 UI:                    YES
    VTK support:                 NO

  Media I/O:
    ZLib:                        build (ver 1.2.13)
    JPEG:                        build-libjpeg-turbo (ver 2.1.3-62)
      SIMD Support Request:      YES
      SIMD Support:              NO
    WEBP:                        build (ver encoder: 0x020f)
    PNG:                         build (ver 1.6.37)
    TIFF:                        build (ver 42 - 4.2.0)
    JPEG 2000:                   build (ver 2.5.0)
    OpenEXR:                     build (ver 2.3.0)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    DC1394:                      NO
    FFMPEG:                      YES (prebuilt binaries)
      avcodec:                   YES (58.134.100)
      avformat:                  YES (58.76.100)
      avutil:                    YES (56.70.100)
      swscale:                   YES (5.9.100)
      avresample:                YES (4.0.0)
    GStreamer:                   NO
    DirectShow:                  YES
    Media Foundation:            YES
      DXVA:                      YES

  Parallel framework:            Concurrency

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2021.8 [2021.8.0]
           at:                   D:/a/opencv-python/opencv-python/_skbuild/win-amd64-3.7/cmake-build/3rdparty/ippicv/ippicv_win/icv
    Intel IPP IW:                sources (2021.8.0)
              at:                D:/a/opencv-python/opencv-python/_skbuild/win-amd64-3.7/cmake-build/3rdparty/ippicv/ippicv_win/iw
    Lapack:                      NO
    Eigen:                       NO
    Custom HAL:                  NO
    Protobuf:                    build (3.19.1)
    Flatbuffers:                 builtin/3rdparty (23.5.9)

  OpenCL:                        YES (NVD3D11)
    Include path:                D:/a/opencv-python/opencv-python/opencv/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python 3:
    Interpreter:                 C:/hostedtoolcache/windows/Python/3.7.9/x64/python.exe (ver 3.7.9)
    Libraries:                   C:/hostedtoolcache/windows/Python/3.7.9/x64/libs/python37.lib (ver 3.7.9)
    numpy:                       C:/hostedtoolcache/windows/Python/3.7.9/x64/lib/site-packages/numpy/core/include (ver 1.17.0)
    install path:                python/cv2/python-3

  Python (for build):            C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe

  Java:
    ant:                         NO
    Java:                        YES (ver 1.8.0.372)
    JNI:                         C:/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk/8.0.372-7/x64/include C:/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk/8.0.372-7/x64/include/win32 C:/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk/8.0.372-7/x64/include
    Java wrappers:               NO
    Java tests:                  NO

  Install to:                    D:/a/opencv-python/opencv-python/_skbuild/win-amd64-3.7/cmake-install
-----------------------------------------------------------------
```

**Comment by opencv-alalek** [comment]
There is wrong usage of environment variables in shell.
Just print them from Python script: `print(os.environ["OPENCV_LOG_LEVEL"])`.
Shell works with environment variables through `export val=value`. Use that.

---

> `camera = cv2.VideoCapture("http://10.0.0.114")`
> `camera.setExceptionMode(True)`

No exception should be raised at all (as expected).
The second statement just can't change execution mode of the first statement.

---

> `camera = cv2.VideoCapture()`
> `camera.setExceptionMode(True)`
> `camera.set(cv.CAP_PROP_OPEN_TIMEOUT_MSEC, 1000)`

Where did you get that code?
`.set()` should be called for opened streams only. In "factory" mode it is an invalid call.
There is dedicated API to pass parameters into .open() method: https://github.com/opencv/opencv/blob/4.8.0/modules/videoio/include/opencv2/videoio.hpp#L803

**Comment by ShyAssassin** [comment]
> Shell works with environment variables through export `val=value`. Use that.

Even when using the `export` keyword the output remains the same.
Printing the environment variable from the python script shows that it is set.

> Where did you get that code?

https://github.com/opencv/opencv/issues/23207#issuecomment-1411945825

> `.set()` should be called for opened streams only.

Only being able to use `.set()` on open streams seems very unintuitive to me it also seems to be missing from [the documentation](https://docs.opencv.org/4.8.0/d8/dfe/classcv_1_1VideoCapture.html#a8c6d8c2d37505b5ca61ffd4bb54e9a7c), along with this the error message provided (even with debug params set) is very ambiguous. It would be nice if a more descriptive error message was output.

<details>
<summary>For reference here is the script that actually works now</summary>

```python
import cv2

camera = cv2.VideoCapture()
camera.setExceptionMode(True)
camera.open("http://localhost:8080", cv2.CAP_FFMPEG, params=[cv2.CAP_PROP_OPEN_TIMEOUT_MSEC, 1000])
```

</details>

**Comment by ribeirompl-soldersmith** [comment]
## Investigation

After looking at the opencv docs about the [video flags](https://docs.opencv.org/4.x/d4/d15/group__videoio__flags__base.html), I noticed that the description for the two timeout properties we're discussing (`CAP_PROP_OPEN_TIMEOUT_MSEC` and `CAP_PROP_READ_TIMEOUT_MSEC`), there was bold text "**open-only**". I didn't know what this meant, but then I saw higher up, that a different property mentioned that the setting is only supported in the VideoCapture constructor.

![image](https://github.com/opencv/opencv/assets/97503920/b32370ca-e3a7-40eb-a06d-1c9e9755f9cd)

## Working Syntax

Based on that info, I did some guess work and managed to get the READ timeout working as follows:
```python
cap = cv2.VideoCapture(
    RTSP_STRING,
    apiPreference=cv2.CAP_ANY,
    params=[cv2.CAP_PROP_READ_TIMEOUT_MSEC, 1000],  # 1 second
)
```

The VideoCapture class requires specifying the `apiPreference`, if you would like to specify `params`, so I chose `cv2.CAP_ANY` which I believe is the default option for it.

The `params` argument requires a list of integers, thus passing the property along with its value worked.

The documentation mentioned that the timeout properties are only applicable to FFmpeg and GStreamer, so as a sanity check I ran `print(cap.getBackendName())` which indeed returned `"FFMPEG"`.

## Testing Example

I tested the system with an IP camera with the following crude script:
```python
import datetime
import cv2

print(datetime.datetime.now(), "Before")
cap = cv2.VideoCapture(
    RTSP_STRING,
    apiPreference=cv2.CAP_ANY,
    params=[cv2.CAP_PROP_READ_TIMEOUT_MSEC, 1000],  # 1 second
)
print(cap.getBackendName())

print(datetime.datetime.now(), "Start")
while True:
    ret, frame = cap.read()

    if not ret:
        print(datetime.datetime.now(), "Error")
        break

    print(datetime.datetime.now(), "Frame")
    cv2.imshow("Live", frame)
    cv2.waitKey(1)
```

After running the script, the output looked as follows:
```
2023-09-22 16:37:17.902359 Before
FFMPEG
2023-09-22 16:37:18.881336 Start
2023-09-22 16:37:18.893302 Frame
2023-09-22 16:37:18.925214 Frame
2023-09-22 16:37:18.928207 Frame
...
```
With it continuously printing "Frame" for each frame received.

I then disconnected the IP camera from the network, and after 1 second (as set in the properties), the cap.read() function timed out and returned False. The output looked as follows:
```
...
2023-09-22 16:37:21.039855 Frame
2023-09-22 16:37:21.080039 Frame
2023-09-22 16:37:22.178844 Error
```

Without setting that property, in the VideoCapture class, the cap.read() function would time out after about 30 seconds, according to some tests I ran.

## Things that don't seem to work

1. After initialising the VideoCapture as above, I tried running: `print(cap.get(cv2.CAP_PROP_READ_TIMEOUT_MSEC))`
However this just returned the value `0.0`.

2. I was unable to get the `cv2.CAP_PROP_OPEN_TIMEOUT_MSEC` property to work. I tried the following:
```python
cap = cv2.VideoCapture(
    RTSP_STRING,
    apiPreference=cv2.CAP_ANY,
    params=[cv2.CAP_PROP_READ_TIMEOUT_MSEC, 1000],  # 1 second
)
```
so that the VideoCapture would time out after 1 second, when attempting to connect to the IP camera (which is disconnected).
However, when testing it, it would only time out after around 60 seconds, and the following error would show in the console:
```
[ERROR:0@62.410] global cap.cpp:166 cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\backend_static.cpp:26: error: (-213:The function/feature is not implemented) VIDEOIO: Failed to apply invalid or unsupported parameter: [53]=1000 / 1000 / 0x000003e8 in function 'cv::applyParametersFallback'
```

Is there perhaps some issue with setting this timeout property when opening the connection? It makes sense that it should be set in the VideoCapture params argument, as that is where the backend connects to the camera, however setting the property does not seem to be supported?

**Comment by ribeirompl-soldersmith** [comment]
UPDATE:

After some more testing, I realised that I need to explicitly select FFMPEG as the backend, otherwise the `CAP_PROP_OPEN_TIMEOUT_MSEC` property won't get set.

```python
cap = cv2.VideoCapture(
    RTSP_STRING,
    apiPreference=cv2.CAP_FFMPEG,  # was previously cv2.CAP_ANY
    params=[cv2.CAP_PROP_OPEN_TIMEOUT_MSEC, 1000],  # 1 second
)
```

This made the open timeout setting work as expected, resulting in the cv2.VideoCapture class initialisation returning early after timing out.

However, as mentioned previously in this discussion, you need to enable ExceptionMode to True, if you want it to raise an error. This has to happen before the connection happens, therefore the following code is required:

```python
cap = cv2.VideoCapture()  # initialise empty VideoCapture class
cap.setExceptionMode(True)
cap.open(
    RTSP_STRING,
    apiPreference=cv2.CAP_FFMPEG,
    params=[cv2.CAP_PROP_OPEN_TIMEOUT_MSEC, 1000],
)
```

However, what still does not work is the `cap.get(cv2.CAP_PROP_READ_TIMEOUT_MSEC)` function call, but that is an unrelated issue, I assume.
