### ISSUE TITLE
OpenCV 4.7.0, masked matchTemplate, TM_CCOEFF_NORMED return "inf" values in C++

### ISSUE THREAD

**Issue by boludoz** [opencv/opencv#23257]
### System Information

// C++ user
OpenCV version: 4.7.0
Operating System / Platform: Windows 11 - 10.0.22621.1105
Compiler & compiler version: Visual Studio 22

### Detailed description

MatchTemplate with mask, gives wrong results with mask usage.

### Steps to reproduce

```
#include <opencv2/opencv.hpp>
#include <iostream>

using namespace cv;
using namespace std;

int main(int argc, char** argv)
{
    // Load source image and template
    Mat src = imread("imagen.png", IMREAD_GRAYSCALE);
    Mat templateImage = imread("imagent.png", IMREAD_GRAYSCALE);

    Mat templateImage_form = imread("imagent.png", IMREAD_UNCHANGED);
	
	// if is ALPHA imagen
	Mat result;
	double tolerance = 0.85;
	if (templateImage_form.channels() == 4) {


		// Separates the image of the template and the alpha mask
		vector<Mat> channels;	
		split(templateImage_form, channels);
		Mat mask = channels[3];

		// Fix mask
		threshold(mask, mask, 1, 255, THRESH_BINARY);
		if (mask.type() != CV_8UC1) {
			mask.convertTo(mask, CV_8UC1);
		}

		auto empty_mask = 0;
		for (int i = 0; i < mask.rows; i++) {
			for (int j = 0; j < mask.cols; j++) {
				if (mask.at<uchar>(i, j) == 0) {
					empty_mask++;
				}
			}
		}
		
		if (empty_mask == 0) {
			// Apply the matchTemplate function with the source image and the template
			std::cout << "mask is not used. Size: " << empty_mask << std::endl;
			matchTemplate(src, templateImage, result, TM_CCOEFF_NORMED);
		} else {
			// Apply the matchTemplate function with the source image and the template
			std::cout << "mask is used. Size: " << empty_mask << std::endl;
			matchTemplate(src, templateImage, result, TM_CCOEFF_NORMED, mask); // < -- BUG IN THIS CASE (mask is used)
		}
	} else {
		// Apply the matchTemplate function with the source image and the template
		matchTemplate(src, templateImage, result, TM_CCOEFF_NORMED);
	}

	// Get all results with tolerance > tolerance
	vector<Point> points;
	for (int i = 0; i < result.rows; i++) {
		for (int j = 0; j < result.cols; j++) {
			if (result.at<float>(i, j) > tolerance) {
				points.push_back(Point(j, i));
			}
		}
	}

	// Draw all points
	for (int i = 0; i < points.size(); i++) {
		rectangle(src, points[i], Point(points[i].x + templateImage.cols, points[i].y + templateImage.rows), Scalar(0, 0, 255), 2);
	}

    // Load the image file to be processed
    imshow("Result", src);
    waitKey(0);

    return 0;
}
```

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

Example images

Image used:
![imagent](https://user-images.githubusercontent.com/11653030/219092639-56439afa-6827-4b42-b004-16d93d1e34fb.png)

**Template used:**
![imagen](https://user-images.githubusercontent.com/11653030/219092646-1eb9f01f-adbe-480a-b7aa-188a0896df8f.png)

Result:
![image](https://user-images.githubusercontent.com/11653030/219093797-38761079-76bd-4160-8e0f-aea201c81649.png)

Color result:
![image](https://user-images.githubusercontent.com/11653030/219094123-6f00734f-f1c7-4bf0-80f6-15e280741a7b.png)

**Another template with small amount of alpha pixels:**
![image](https://user-images.githubusercontent.com/11653030/219094613-f2fe25a9-0e42-4aed-8d2f-08c4741c2cd5.png)

Result:
![image](https://user-images.githubusercontent.com/11653030/219094793-dffbdc3b-acf8-4123-87f9-53b08299d6e0.png)

**No alpha template, no mask:**
![image](https://user-images.githubusercontent.com/11653030/219094971-fea2eb1e-b6a9-4a69-87bf-4e3cd0bd6d59.png)

Result:
![image](https://user-images.githubusercontent.com/11653030/219095043-b648d43d-f21a-4dcd-9e1b-178282c1b653.png)

**Same code with 'TM_CCORR_NORMED' and 0.99 of threshold and color image:**

**Template:**
![image](https://user-images.githubusercontent.com/11653030/219098159-406c6eac-893c-43f4-8eec-4370010ccb59.png)

Result
![image](https://user-images.githubusercontent.com/11653030/219098067-9f1f9263-12e5-48c7-99c0-fc3737ac87c3.png)

Same template of back result, TM_SQDIFF_NORMED and 0.15 and inverted tolerance symbol:

Results
![image](https://user-images.githubusercontent.com/11653030/219099994-50f6a422-5f6a-4060-915b-d8d85bf33c73.png)

![image](https://user-images.githubusercontent.com/11653030/219100086-1c7927c6-df9f-41ad-ab1e-57a50d44ba25.png)

**Comment by boludoz** [comment]
I fixed that with:

```
			// Check infinite values
			if (point == INFINITY) {
				point = 0;
			}	

```

The bug is that it returns infinite values ​​wrongly.

`Point: 352, 83, T: 0.866379
Point: 353, 83, T: 0.999999
Point: 354, 83, T: 0.86649
Point: 555, 113, T: inf
Point: 556, 113, T: inf
Point: 557, 113, T: inf
Point: 558, 113, T: inf
Point: 559, 113, T: inf
Point: 560, 113, T: inf
Point: 561, 113, T: inf
Point: 562, 113, T: inf
Point: 563, 113, T: inf
Point: 564, 113, T: inf
Point: 565, 113, T: inf
Point: 566, 113, T: inf
Point: 567, 113, T: inf
Point: 569, 113, T: inf
Point: 570, 113, T: inf
Point: 571, 113, T: inf
Point: 572, 113, T: inf
Point: 573, 113, T: inf
Point: 574, 113, T: inf
Point: 575, 113, T: inf
Point: 576, 113, T: inf
Point: 577, 113, T: inf
Point: 556, 115, T: inf
Point: 557, 115, T: inf
Point: 554, 116, T: inf
Point: 555, 116, T: inf
Point: 556, 116, T: inf
Point: 634, 172, T: inf
Point: 636, 172, T: inf
Point: 637, 172, T: inf
Point: 638, 172, T: inf
Point: 639, 172, T: inf
Point: 640, 172, T: inf
Point: 641, 172, T: inf
Point: 642, 172, T: inf
Point: 643, 172, T: inf
Point: 644, 172, T: inf
Point: 645, 172, T: inf
Point: 633, 173, T: inf
Point: 717, 199, T: inf
Point: 717, 200, T: inf
Point: 685, 201, T: inf
Point: 689, 201, T: inf
Point: 690, 201, T: inf
Point: 691, 201, T: inf
Point: 692, 201, T: inf
Point: 693, 201, T: inf
Point: 694, 201, T: inf
Point: 700, 201, T: inf
Point: 701, 201, T: inf
Point: 704, 201, T: inf
Point: 705, 201, T: inf
Point: 707, 201, T: inf
Point: 708, 201, T: inf
Point: 709, 202, T: inf
Point: 710, 202, T: inf
Point: 711, 202, T: inf
Point: 711, 203, T: inf
Point: 714, 204, T: inf
Point: 715, 205, T: inf
Point: 716, 205, T: inf
Point: 585, 207, T: inf
Point: 586, 208, T: inf
Point: 586, 209, T: inf
Point: 590, 212, T: inf
Point: 591, 212, T: inf
Point: 754, 247, T: inf
Point: 755, 247, T: inf
Point: 756, 247, T: inf
Point: 757, 247, T: inf
Point: 758, 247, T: inf
Point: 759, 247, T: inf
Point: 760, 247, T: inf
Point: 761, 247, T: inf
Point: 762, 247, T: inf
Point: 763, 247, T: inf
Point: 764, 247, T: inf
Point: 765, 247, T: inf
Point: 766, 248, T: inf
Point: 767, 248, T: inf
Point: 768, 248, T: inf
Point: 769, 248, T: inf
Point: 759, 282, T: inf
Point: 760, 282, T: inf
Point: 761, 282, T: inf
Point: 762, 282, T: inf
Point: 743, 291, T: inf
Point: 767, 325, T: inf
Point: 724, 329, T: inf
Point: 725, 329, T: inf
Point: 726, 329, T: inf
Point: 727, 329, T: inf
Point: 728, 329, T: inf
Point: 729, 329, T: inf
Point: 730, 329, T: inf
Point: 731, 329, T: inf
Point: 732, 329, T: inf
Point: 735, 329, T: inf
Point: 735, 330, T: inf
Point: 735, 331, T: inf
Point: 697, 460, T: inf
Point: 696, 461, T: inf
Point: 697, 461, T: inf
Point: 709, 463, T: inf
Point: 695, 466, T: inf
Point: 693, 467, T: inf
Point: 694, 467, T: inf
Point: 693, 468, T: inf
Point: 694, 468, T: inf
Point: 686, 469, T: inf
Point: 687, 469, T: inf
Point: 688, 469, T: inf
Point: 689, 469, T: inf
Point: 706, 469, T: inf
Point: 685, 470, T: inf
Point: 694, 471, T: inf
Point: 697, 471, T: inf
Point: 698, 471, T: inf
Point: 699, 471, T: inf
Point: 700, 471, T: inf
Point: 701, 471, T: inf
Point: 702, 471, T: inf
Point: 703, 471, T: inf
Point: 704, 471, T: inf
Point: 705, 471, T: inf
Point: 697, 472, T: inf
Point: 698, 472, T: inf
Point: 699, 472, T: inf
Point: 700, 472, T: inf
Point: 701, 472, T: inf
Point: 702, 472, T: inf
Point: 703, 472, T: inf
Point: 704, 472, T: inf
Point: 705, 472, T: inf`

**Comment by boludoz** [comment]
The error occurs in the final division performed in maked "matchTemplate" which gives an erroneous result and is not handled in the original function. This in python would not happen (joking).

**Comment by 4piu** [comment]
I am using `4.9.0.80` on Windows and this issue still persists. 

```py
res = cv2.matchTemplate(img, template, cv2.TM_CCOEFF_NORMED, mask=mask)

>>> np.count_nonzero(res == np.inf)
83
```

I can make a workaround with `res[res == np.inf] = -1`, but I hope this can be fixed soon. 
Also be aware the float value can be slightly larger than 1 or smaller than -1.

**Comment by Huyiton** [comment]
I am still experiencing this issue on Windows with Python 3.10 using OpenCV version 4.10.0.84. I added a line of code that solved it:
result = cv2.matchTemplate(original_image, template_image_path, cv2.TM_CCOEFF_NORMED, mask=mask)
result[np.isinf(result)] = 0
Thanks to the original poster for the idea.

**Comment by ershat-dl** [comment]
> The error occurs in the final division performed in maked "matchTemplate" which gives an erroneous result and is not handled in the original function. This in python would not happen (joking).
> 
> The operating range should be between 0 and 1, therefore it is a bug, considering that TM_CCOEFF_NORMED is the "most accurate" method it is a really important error.

How can I fix the error by modifing source code? Any suggestions? thanks.

**Comment by JohnHardy** [comment]
In our impl we convert any very low denomonators to
