### ISSUE TITLE
opencv.js: Suspicious use of the "!" operator inside the "instanceof" operator

### ISSUE THREAD

**Issue by andreialecu** [opencv/opencv#26158]
### Detailed description

The generated opencv.js file seems to contain the following code:

```
...y{table.grow(1)}catch(err){if(!err instanceof RangeError){throw...
```

That's incorrect, as it will first negate err. The correct code would be `if (!(err instanceof RangeError))`

### Issue submission checklist

- [X] I report the issue, it's not a question
- [ ] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [ ] I updated to the latest OpenCV version and the issue is still there
- [ ] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by andreialecu** [comment]
Can be found at https://docs.opencv.org/4.x/opencv.js

This is probably caused by an old version of emscripten being used.

**Comment by asmorkalov** [comment]
OpenCV team updated emscripten tools after release 4.10.0. So it should be already fixed in coming 4.11.

**Comment by opencv-alalek** [comment]
> OpenCV team updated emscripten tools after release 4.10.0. So it should be already fixed in coming 4.11.

That is not true.

Upgraded versions of build images were prepared (have `-3.1.64` suffix) but they are not used by default.
As they require additional fixes which are not landed in the source tree (#25896 just closed).

Problem is still here - just download .js from the site.

**Comment by opencv-alalek** [comment]
Switched builder, but there are many warnings: https://pullrequest.opencv.org/buildbot/builders/4_x-contrib_docs-lin64/builds/100984
