### ISSUE TITLE
latest ubuntu 16.04 server: build error

### ISSUE THREAD

**Issue by avtomaton** [opencv/opencv#7575]
##### System information (version)
- OpenCV => 3.1 (master, ecb8fb964d2dfe9ade00edc11d4119f997360bab)
- Operating System / Platform => ubuntu 16.04 LTS server 64-bit
- Compiler => GCC 5.4
##### Detailed description

During build I have the following error:
[ 40%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o
make[2]: **\* No rule to make target '/usr/include/x86_64-linux-gnu/../lib/libavcodec.a', needed by 'lib/libopencv_videoio.so.3.1.0'.  Stop.

All ffmpeg-related stuff is installed, I see in cmake output:
--     FFMPEG:                      YES
--       codec:                     YES (ver Unknown)
--       format:                    YES (ver Unknown)
--       util:                      YES (ver Unknown)
--       swscale:                   YES (ver Unknown)
--       resample:                  YES (ver Unknown)
--       gentoo-style:              YES
##### Steps to reproduce

```
git clone http://github.com/opencv/opencv
cd opencv
mkdir build && cd build
cmake -D CMAKE_BUILD_TYPE=Release ..
make
```

**Comment by avtomaton** [comment]
Actually the problem appears just because pkg-config is missed in described system and I see no any warning in cmake output, but build can't be done correctly. Not sure that issue should be fixed, and not sure where I can post this info. Possibly pkg-config should be in dependencies?

**Comment by DiaLight** [comment]
Ensure, you have all the dependencies resolved.
http://docs.opencv.org/3.1.0/d7/d9f/tutorial_linux_install.html
Probably you need to install libavcodec-dev.
sudo apt-get install libavcodec-dev

**Comment by avtomaton** [comment]
Have you read it carefully? I mentioned that ALL dependencies are installed (please look at cmake output: YES for all ffmpeg-related stuff). The only problem is in cmake checks: without pkg-config it checks only headers presence in system, not libraries. It leads to errors, because during build it tries to find libraries in some guessed ffmpeg root (i. e. in <header path>/../lib), but in linux it's wrong path: libraries are in /usr/lib or in /usr/lib/*-linux-gnu).

**Comment by StevenPuttemans** [comment]
@avtomaton if I remember it correct the installation guides clearly state you need `build-essentials` as dependencies, which in turn contains a fully working `pkg-config` manager. So I agree that all dependencies should be fulfilled as stated by @DiaLight. Probably you missed that small dependency somewhere ...

**Comment by avtomaton** [comment]
@StevenPuttemans I already know why it doesn't work, and problem is solved. I just wanted to point out that without pkg-config there is no any error during cmake stage (everything is OK, everything is found), but actually opencv can't be built correctly. And build error is not so obvious. My suggestion is either fix ffmpeg-related cmake script to provide also libraries lookup (I can make PR if needed), or provide pkg-config dependency check in cmake stage, or just close this issue. It is not critical at all.

**Comment by ahmedammar** [comment]
@StevenEWright @avtomaton this was very useful I hit exactly the same issue, the problem is `build-essential` on 16.04 server seems to not include `pkg-config` binary any more ...

**Comment by arpit1997** [comment]
I already know why it doesn't work, and problem is solved. I just wanted to point out that without pkg-config there is no any error during cmake stage (everything is OK, everything is found), but actually opencv can't be built correctly. And build error is not so obvious. My suggestion is either fix ffmpeg-related cmake script to provide also libraries lookup (I can make PR if needed), or provide pkg-config dependency check in cmake stage, or just close this issue. It is not critical at all.

**Comment by StevenPuttemans** [comment]
@arpit1997 Go ahead and make a PR ;)

**Comment by alalek** [comment]
You can take a look on approach from PR #7743 into 2.4 branch (It will be ported into master soon)

**Comment by arpit1997** [comment]
Thanks @stevenputtemans. I verified the approach for fixing this but I can't make a PR because I don't have environment to test the PR build so if someone else can make this work then it would be so good

**Comment by StevenPuttemans** [comment]
@arpit1997 like @alalek just said, the fix is in and will be ported into master soon.
