### ISSUE TITLE
Get rid of finalizers in Java bindings

### ISSUE THREAD

**Issue by sgjava** [opencv/opencv#8683]
[Oracle recommends axing Java object finalizer](http://www.javaworld.com/article/3186687/java-language/oracle-recommends-axing-java-object-finalizer.html) and I've written why finalizers are evil [OpenCV Java memory management ](https://github.com/sgjava/opencvmem). I put PRs in a while ago with a solution, but they were rejected. https://github.com/opencv/opencv/pull/4056

**Comment by alalek** [comment]
- Current JVM garbage collector is not able to count used memory by native code (JNI).
- We happy to see more robust destructor for native(JNI) Java objects. What approach is suggested?

**Comment by sgjava** [comment]
There's no clean way to do it implicitly because weak references and system.gc() are also considered bad practice. The explicit way I've been doing it would be:

```
@Override
protected void finalize() throws Throwable {
    n_delete(nativeObj);
    super.finalize();
}
```

Change to:

```
public void free() {
    if (nativeObj != 0) {
        release();
        n_delete(nativeObj);
        nativeObj = 0;
    }
}
```
You cannot mimic the Python and C++ API in Java JVM using a finalizer. You could of course add a free method, so as not to break older code. You'd need to set nativeObj to 0, so  n_delete is not called twice in case free is called more than once.

**Comment by sgjava** [comment]
This is still in 4.0.0-pre

**Comment by alalek** [comment]
JVM has no other ways to properly cleanup **native** objects, so we using `finalize()` methods.

> add a free method

How do you want to properly call your custom free methods during exception raising?


Finally, JVM is not able to track native memory usage. Java's Mat is just several bytes for storing native address (via long). So then you creating 1000 3megapixel images, for Java it is just several kilobytes, but really it is 10Gb.
This can't be fixed in OpenCV without proper support from Java side.

Anyway you can always do manual memory management and call `release()` methods (instead your free, which has similar effect and frees image data).
Also workaround with `System.gc()` (every frame, ten frames, etc) works on many platforms (however Java standard says nothing good about that).

**Comment by sgjava** [comment]
I may generate JNA code for the opencv libs, so you end up using the native methods any ways. I'm already generating libgpiod  wrapper using JNAerator. It would be worth trying on one opencv library and see what happens :)

free() deletes the native object. release() will free the native Mat, but leak the native object it was attached to. I cover all the various clean up  methods and why some are better than others. https://github.com/sgjava/opencvmem

**Comment by kvnxiao** [comment]
I still don't understand why this issue is being ignored. Just got bit in the arse today by the native memory accumulating at an alarming rate but never being freed, even with explicit Mat#release() calls. I would certainly appreciate not having to call System.gc() every ten seconds or so.

@sgjava I've read over your `opencvmem` README. What would be the best approach in my use case if I am essentially feeding in image data (as .PNG format) from an android phone over ADB to a desktop java OpenCV application, which generates Mat files every 300-400 ms through `Imgcodecs.imdecode(MatOfByte(byteArray))` ?

**Comment by sgjava** [comment]
The only way I found was by patching the code in OpenCV. Change patchjava="True" in https://github.com/sgjava/install-opencv/blob/master/scripts/config.sh before building. Take a peek at https://github.com/sgjava/install-opencv/blob/7d3ea27dae87ec3be7503a3ff8307d8f30f5556a/scripts/install-opencv.sh#L80 to see what I'm patching. There still could be other places for leaks, but this covers 95% of them.

As you have figured out release doesn't remove nativeObj until System.gc() is called. I've tired of explaining/proving why this is a bad thing. Someone that suggests calling System.gc() periodically as a fix cannot be take seriously.

**Comment by kvnxiao** [comment]
@sgjava Just curious, is your `install-opencv` repo updated to latest opencv 4.1.2? And do I simply only need the final compiled .jar file with the patched fixes? The pretext is that I am going to be running this on a Windows machine.

**Comment by sgjava** [comment]
Actually it defaults to master, so I think current build is 4.2.0-dev. You can change the install script to use whatever branch you want though. The Java bindings should match the OpenCV version installed. But in essence what you are describing should work. If you'd like to discuss further create issue on my project.
